### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'invmove'!

### ISSUE THREAD

**Issue by MrTechnobladers** [PieKing1215/InvMove#45] opened 2024-02-22 17:51 UTC
**Version and Mod List**
List the version of InvMove, the version of Forge/Fabric/Quilt, and the version of Minecraft the issue happens on:
InvMove: v0.8.5
Forge/Fabric/Quilt version: 0.15.7
Minecraft: 1.20.2
**Issue**
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'invmove'!
[crash-2024-02-22_17.43.18-client.txt](https://github.com/PieKing1215/InvMove/files/14377572/crash-2024-02-22_17.43.18-client.txt)

**Comment by PieKing1215** [comment] 2024-02-25 08:53
Duplicate of gh-43

**Closed as not planned by PieKing1215** 2024-02-25 08:53 UTC
Labels: bug
