### ISSUE TITLE
1.20 needed

### ISSUE THREAD

**Issue by ToiletKun** [PieKing1215/InvMove#33] opened 2023-06-15 18:29 UTC
It's difficult to adapt to 1.20 without Invmove after getting used to it......However I saw the update 5 days ago on the page, I was wandering when could we get the version for 1.20?

**Comment by PieKing1215** [comment] 2023-06-15 22:38
Probably will release on Modrinth this weekend, in the meantime you can use the dev build from gh-32, which seems to be working fine

(duplicate of gh-32)

**Closed as not planned by PieKing1215** 2023-06-15 22:38 UTC
Labels: enhancement

**Comment by ToiletKun** [comment] 2023-06-16 09:47
> Probably will release on Modrinth this weekend, in the meantime you can use the dev build from [gh-32](https://github.com/PieKing1215/InvMove/issues/32), which seems to be working fine
> 
> (duplicate of [gh-32](https://github.com/PieKing1215/InvMove/issues/32))

thanks a lot.  it works perfect.

**Comment by PieKing1215** [comment] 2023-06-19 00:05
Version [0.8.4](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.4) (with 1.20 support) is out on [Modrinth](https://modrinth.com/mod/invmove/versions)!
I set it as alpha because I didn't have time to manually test every version/loader combo, but I didn't want to keep everyone waiting when it seems like it's working fine (feel free to open issues if there's any problems).
