### ISSUE TITLE
Crash on lauch

### ISSUE THREAD

**Issue by KathaiArt** [PieKing1215/InvMove#44] opened 2024-02-02 16:39 UTC
When trying to lauch the game, it crashes.

**Version and Mod List**
InvMove: v0.8.5 (1.20) (Alpha)
Fabric version: 0.15.6
Minecraft: 1.20.4

Mod List:
Zoomify-2.13.0.jar
AdvancementPlaques-1.20.4-fabric-1.5.1.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.20.3-2.5.1.jar
balm-fabric-1.20.4-9.0.5.jar
BetterCompatibilityChecker-fabric-5.1.1+mc1.20.4.jar
BetterF3-9.0.0-Fabric-1.20.4.jar
bettermounthud-1.2.2.jar
BetterPingDisplay-Fabric-1.20.4-1.1.1.jar
borderless-mining-1.1.9+1.20.2.jar
capes-1.5.3+1.20.2-fabric.jar
chat_heads-0.10.31-fabric-1.20.3.jar
chatanimation-1.0.5.jar
chesttracker-2.2.3+1.20.4.jar
chunksfadein-v1.0.2-1.20.2.jar
ClientHarvest-1.0.3.jar
cloth-config-13.0.121-fabric.jar
collective-1.20.4-7.30.jar
continuity-3.0.0-beta.4+1.20.2.jar
Controlify-1.8.1+1.20.4.jar
Controlling-fabric-1.20.4-15.0.2.jar
Debugify-1.20.4+1.0.jar
dynamic-fps-3.3.3+minecraft-1.20.0.jar
e4mc-4.0.1+1.19.4-fabric.jar
eating-animation-1.20+1.9.5.jar
enhancedblockentities-0.9.1+1.20.2.jar
entity_model_features_fabric_1.20.4-1.2.3.jar
entity_texture_features_fabric_1.20.4-5.2.2.jar
entityculling-fabric-1.6.3.1-mc1.20.4.jar
EquipmentCompare-1.20.2-fabric-1.3.8.jar
essential_1-3-0-3_fabric_1-20-4.jar
fabric-api-0.95.1+1.20.4.jar
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
fabricskyboxes-0.7.3+mc1.20.2.jar
fabrishot-1.12.1.jar
fastquit-3.0.0+1.20.4.jar
ferritecore-6.0.3-fabric.jar
firstperson-fabric-2.3.2-mc1.20.4.jar
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
fsb-interop-1.3.6+mc1.20.2-build.52.jar
held-item-info-1.5.0.jar
Iceberg-1.20.4-fabric-1.1.18.jar
ImmediatelyFast-Fabric-1.2.8+1.20.4.jar
indium-1.0.28+mc1.20.4.jar
inventorymanagement-1.5.0+1.20.3.jar
InvMove-1.20-0.8.5-Fabric.jar
iris-mc1.20.4-1.6.15.jar
Ksyxis-1.2.2.jar
language-reload-1.5.10+1.20.3.jar
LegendaryTooltips-1.20.2-fabric-1.4.5.jar
litematica-fabric-1.20.4-0.17.0.jar
lithium-fabric-mc1.20.4-0.12.1.jar
main-menu-credits-1.1.2.jar
malilib-fabric-1.20.4-0.18.0.jar
mixintrace-1.1.1+1.17.jar
ModDetectionPreventer+1.20.4-1.1.0.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.12.1+mc1.20.4.jar
modmenu-9.0.0.jar
morechathistory-1.3.0.jar
moreculling-1.20.4-0.22.1.jar
mousewheelie-1.13.3+mc1.20.4.jar
NoChatReports-FABRIC-1.20.4-v2.5.0.jar
notenoughanimations-fabric-1.7.0-mc1.20.4.jar
optigui-2.1.7.jar
paginatedadvancements-2.4.2.jar
Prism-1.20.4-fabric-1.0.6.jar
puzzle-1.6.1+1.20.4.jar
reeses_sodium_options-1.7.1+mc1.20.4-build.100.jar
replaymod-1.20.4-2.6.14.jar
rrls-3.3.0+mc1.20.4-fabric.jar
Searchables-fabric-1.20.4-1.0.3.jar
shulkerboxtooltip-fabric-4.0.8+1.20.4.jar
skinlayers3d-fabric-1.6.2-mc1.20.4.jar
smoothgui-0.1.0.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
sodium-fabric-0.5.7+mc1.20.3.jar
sound-physics-remastered-fabric-1.20.4-1.3.1.jar
status-effect-bars-1.0.4.jar
treeharvester-1.20.4-8.6.jar
tweakeroo-fabric-1.20.4-0.19.1.jar
voicechat-fabric-1.20.4-2.5.1.jar
waystones-fabric-1.20.4-16.0.3.jar
whereisit-2.3.4+1.20.4.jar
Xaeros_Minimap_23.9.7_Fabric_1.20.4.jar
xaeros-map-chest-tracker-integration-mc1.20.4-v2.0.1.jar
XaerosWorldMap_1.37.8_Fabric_1.20.4.jar
yet-another-config-lib-fabric-3.3.2+1.20.4.jar
yosbr-0.1.2.jar

[crash-2024-02-02_13.22.38-client.txt](https://github.com/PieKing1215/InvMove/files/14142725/crash-2024-02-02_13.22.38-client.txt)

[latest.log](https://github.com/PieKing1215/InvMove/files/14142727/latest.log)

**Comment by PieKing1215** [comment] 2024-02-02 21:26
Duplicate of gh-43

**Closed as not planned by PieKing1215** 2024-02-02 21:26 UTC
Labels: bug
